### ISSUE TITLE
If using a reserved keywords as a column

### ISSUE THREAD

**Issue by nandehu0323** [mercari/yo#8]
Nice to meet you. I have a question this time and I have created an issue.
First of all, thanks for creating such a wonderful tool.
It is very helpful.

I have a question: 
If I use reserved words as columns, may need to backquote them when I issue the query.
[https://cloud.google.com/spanner/docs/data-definition-language#reserved_keywords](https://cloud.google.com/spanner/docs/data-definition-language#reserved_keywords)

In automatically generated code, reserved words are not enclosed in backquotes, which results in an error when the function is executed.
```
spanner: code = "InvalidArgument", desc = "Syntax error: Unexpected keyword HASH...
```

Is there any way to avoid this error?
If not, do you plan to implement it in the future?

If there is no plan to implement it, is it possible to merge the PR after I fix it?

I look forward to your reply.
Kind Regards,

**Comment by kazegusuri** [comment]
Thank you for the report. There is no plan for now and of course I appreciate a PR.

**Comment by nandehu0323** [comment]
https://github.com/mercari/yo/pull/9

I made PR to fix this issue.
Please check it.
